version: '3.5'

services:
    mailcatcher:
      container_name: mailcatcher
      image: schickling/mailcatcher
      ports:
          - 1080:1080
          - 1025:1025
      networks:
          - default-services

    rabbitmq:
        image: rabbitmq:3.7-management
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_USER: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - default-services
networks:
    default-services:
